# DOCKERFILE for seq_typing https://github.com/B-UMMI/seq_typing
FROM odiogosilva/rematch:latest
MAINTAINER Diogo N. Silva, diogosilva@medicina.ulisboa.pt

WORKDIR /NGStools

RUN git clone https://github.com/B-UMMI/seq_typing.git
ENV PATH="/NGStools/seq_typing:$PATH"

